### ISSUE TITLE
Not all levels highlighted correctly

### ISSUE THREAD

**Issue by monkeycoder99** [chingucoding/IndentRainbow#9] opened 2019-09-07 00:19 UTC
See attached image. There should be highlights at all tab stops before braces, but they're missing. Also, the last level before text seems to be missing on every line. I like the idea and I too love the extension for VSC as well.

![image](https://user-images.githubusercontent.com/35289977/64467057-0ce7cd80-d0ca-11e9-92b1-5768d9357b8b.png)

**Comment by chingucoding** [comment] 2019-09-07 00:26
Okay I am a bit confused as to why I was not able to see this behavior before, since I have been using my extension unsurprisingly since day one.

Do you have a sample (file) that triggers this behavior consistently?
Which version of Visual Studio are you using and which version of IndentRainbow are you using?
Which settings are you using for IndentRainbow (colors,alpha value, etc)?

**Comment by chingucoding** [comment] 2019-09-21 19:54
Closing this as I can not reproduce the bug in question.

**Closed by chingucoding** 2019-09-21 19:54 UTC

**Comment by chingucoding** [comment] 2019-10-09 21:41
I think I was able to reproduce your bug and created a fix for this in version 0.4.1 of the extension. Please tell me if that fixed your problem 😄

**Comment by monkeycoder99** [comment] 2019-10-10 23:12
Thanks for looking into this. I installed 0.4.1 and I'm still having the problem. Here's some SS for .json and .cs. It may have improved to just being an issue for braces ("{", "}").
![image](https://user-images.githubusercontent.com/35289977/66612904-68e5bc00-eb78-11e9-9e7c-44519f33c46c.png)
![image](https://user-images.githubusercontent.com/35289977/66612928-7dc24f80-eb78-11e9-9c09-562b3eb18de5.png)

**Comment by chingucoding** [comment] 2019-10-11 16:30
Okay, I think I fixed it now with version 0.4.1.1 . Again, please tell me if this fixed your issue. 😅

**Comment by monkeycoder99** [comment] 2019-10-11 16:58
That's it! You got it. Looks great now. Thanks again.

**Comment by chingucoding** [comment] 2019-10-11 17:03
> That's it! You got it. Looks great now. Thanks again.

No problem. Thanks for reporting the issue and checking so quickly if the fix works for you!
